server:
  port: 8002

spring:
  application:
    name: article
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    prefer-ip-address: true
xiandada:
  name: push-config123456
